### ISSUE TITLE
Send Campaign ID to MC

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#109]
## Overview
The campaign ID we get from a user in the MailChimp campaign email, we set in a cookie, but don't send back to MailChimp on an order. We should send this value back to Mailchimp on the order object. This is a required field in order to do product recommendations. 

- [x] Drupal Commerce D7
- [x] Drupal Commerce D8
- [x] Drupal Ubercart D7
- [ ] Drupal Ubercart D8

**Comment by mshaver** [comment]
Collecting campaign_id in cookie for all, but need to send with oder for D8 ubercart.

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mailchimp eCommerce Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp_ecommerce/issues/3051100
