### ISSUE TITLE
Add store domain when creating a store

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#110]
## Overview
The store domain is required in the product recommendations in MC. We can add this value when creating a store. 

- [x] Drupal Commerce D7
- [ ] Drupal Commerce D8
- [ ] Drupal Ubercart D7
- [ ] Drupal Ubercart D8

**Comment by mshaver** [comment]
Related issue https://www.drupal.org/project/mailchimp_ecommerce/issues/2903701

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mailchimp eCommerce Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp_ecommerce/issues/3051099
