### ISSUE TITLE
Reconfigure connected sites selection options to default to current domain first

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#111]
## Overview
The current connected sites selection process shows all connected sites for a list, which can be confusing for users. MailChimp's preference is to default to the current domain you are on first and if that doesn't match a connected site domain, offer a selection of domains to choose from. In theory most sites connecting to MailChimp will have a store with their domain, but it is possible dev environments will require connecting to alternative domains. 

Relates to #91

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mailchimp eCommerce Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp_ecommerce/issues/3051098
