### ISSUE TITLE
Handle Duplicate Stores

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#129]
Stores are required to be unique per domain name now. So, we must handle store deletes when uninstalling and if we create a store that already exists, we must give the user a chance to delete the store, or reuse the old store and proceed!

**Comment by mshaver** [comment]
Check for existing store in MC and allow user to choose it. 
 * Existing or New

Uninstall Module
 * Allow user to choose to delete store in MC 
 * Lots of warnings for this!!!!!

**Comment by mortenson** [comment]
👋 Hi there - we're moving all existing Mailchimp eCommerce Github issues and pull requests to Drupal.org so that we can track work in one place. If the copied Drupal.org issue is missing information please edit it or add a comment.

The new issue is located at https://www.drupal.org/project/mailchimp_ecommerce/issues/3051097
