### ISSUE TITLE
Implement line item hooks in mailchimp_ecommerce_commerce

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#13]
Order line items:
- [ ] Create order line item: hook_commerce_line_item_insert()
  - [x] D7 ecommerce
  - [x] D8 ecommerce
  - [ ] D7 ubercart
  - [ ] D8 ubercart

- [ ] Update order line item: hook_commerce_line_item_update()
  - [x] D7 ecommerce
  - [x] D8 ecommerce
  - [ ] D7 ubercart
  - [ ] D8 ubercart

- [ ] Delete order line item: hook_commerce_line_item_delete()
  - [x] D7 ecommerce
  - [x] D8 ecommerce
  - [ ] D7 ubercart
  - [ ] D8 ubercart

**Comment by mshaver** [comment]
I'm moving this to "Done", let me know @ruscoe if that is incorrect.

**Comment by torgospizza** [comment]
This doesn't look done for me (at least as far as I can tell). Also I don't believe we should react to line_item_insert, since that doesn't always mean a product is being added. Please take a look at my PR in #113, as I'm implementing cart hooks (`product_add`, `product_remove`) and a couple of order-specific hooks (`update` and `delete`). If we find that we need others such as `insert` then I can add those next.

**Comment by mortenson** [comment]
Associated PR has been closed, assuming this is done now.
