### ISSUE TITLE
Do not track new carts

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#32]
We should only track carts that have valid email addresses attached to them because Mailchimp requires a valid email. So, we should only track partial carts for logged in users.

**Comment by taz77** [comment]
What exactly is tracked?

**Comment by taz77** [comment]
I read the API documentation. As a merchant, I will want the ability to track all carts - even for non-logged in users. So I would say to allow this to be turned on/off but don't remove it completely from the module. My Drupal Commerce store has thousands of anonymous carts from active users. They just start adding stuff to their cart and never check out. I would like to create an abandoned cart workflow in Mailchimp to reach out to these people, but if you don't track carts for anonymous users then this is not possible.

**Comment by Greg-Boggs** [comment]
I agree with you. The email field is required to send results to mailchimp. We could fill in fake email addresses, but for most folks, those fake emails would then end up as recipients to an email list. I will bring this issue up with the MailChimp team to see if they have any thoughts. For your specific use case, this module will check to see if users have an email. We can add a hook to the check. So, on your site, just implement the hook, set a fake email, and then make sure not to put the anonymous fake emails into a mailing list... Involved for sure!

**Comment by taz77** [comment]
Ok cool. I will keep watch on this thread and I'm going to take a look at the anonymous carts I have now.

**Comment by taz77** [comment]
Hrm, I may have another idea. Let me look at more empirical data in my shopping cart (I have over 13500 incomplete shopping carts!). I think I am seeing a trend that could help with this problem. There may be a good point in the checkout process to start tracking the information.

**Comment by Greg-Boggs** [comment]
My assumption is that the tool is focused 100% not just on tracking, but letting marketers take action by emailing folks. So, that might explain why they don't accept any information that doesn't have an email attached to it. But, I haven't talked to the MC team about it yet.

**Comment by taz77** [comment]
From what I am seeing is there is not a valid email address on a shopping cart that is of the status "Shopping Cart". When the status changes to "Checkout: XXXXXX" is when you have a valid email address. If my memory is correct there are hooks in commerce for reacting to the status change of the carts. If true, that could be used.

**Comment by torgospizza** [comment]
We might improve things by making sure Carts are only sent if their state is "in_checkout" as opposed to "in_cart" since a shopping cart itself can be volatile as users add and remove products. In most cases we probably don't care what a user does up until they enter Checkout, so it might be a good idea to only send carts to MC once the user has begun the Checkout process.

EDIT: One way to do this would be to invoke `hook_commerce_order_update()` to react on order save hooks. We could also do this with Rules and the "After saving an existing order" event.

The other way would be just within the `_mailchimp_ecommerce_commerce_build_order()` callback, to check that the order state is one of `cart` or `completed`. For example:
`$cart_statuses = array_keys(commerce_order_statuses(array('state' => 'cart')));`
`$complete_statuses = array_keys(commerce_order_statuses(array('state' => 'completed')));`

**Comment by Greg-Boggs** [comment]
I believe if someone adds a product to the cart, and we already have their email, that we want to track that cart as an abandoned cart so that MC can email them with a transaction email that says: "You added these funny movies to your cart, but never hit checkout!"

**Comment by torgospizza** [comment]
Yeah, that makes sense. Since we're doing the `_send_cart()` stuff through Rules, it's probably a non-issue.

**Comment by mshaver** [comment]
As designed
