### ISSUE TITLE
Product Recommendations

### ISSUE THREAD

**Issue by Greg-Boggs** [thinkshout/mailchimp_ecommerce#69]
## Overview
To support product recommendations, we must sync more product details from each of the ecommerce options. You can see from the API that we'll need certain values for a user to use these and that some will require additional optional Drupal Commerce modules. 

**Product guide:** 
https://mailchimp.com/features/product-recommendations/

**API guide:** 
https://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/products/

1. Sync Product Image
2. Sync Product URL
3. Sync Product stock quantity (requires extra module for each cart)

**Comment by torgospizza** [comment]
Regarding product images, since Commerce does not specify a canonical field for images, I'm thinking we should include a select list that includes any Image fields used in Product entity types. That way the store admin can select which image field to include with the product data as it is sent to MailChimp.

**Comment by Greg-Boggs** [comment]
Yup. I agree.
