### ISSUE TITLE
Order History: Sync historical orders

### ISSUE THREAD

**Issue by mshaver** [thinkshout/mailchimp_ecommerce#82]
## Overview
Sync historical orders. MailChimp has identified that only 6 months of data is necessary and most stores would only need this amount to sync. 

- [x] D7 Commerce
- [x] D7 Ubercart
- [x] D8 Commerce
- [x] D8 Ubercart

**Comment by torgospizza** [comment]
Only 6 months is necessary, but at least in some cases (ours!) we have one-off products that we may not want to recommend to folks if they already have purchased them. So that being said, perhaps the UI could include several options for how far back the historical data should go that gets synced.

**Comment by Greg-Boggs** [comment]
I believe there's a field for active status on products, we could pass the active/inactive status? I assume your old products aren't still published?

**Comment by torgospizza** [comment]
There is a `status` field on commerce product entities, yes. 

However, our products are "non-consumable" - they're always available if they are published; for the _most_ part, users will only ever own one, because the products are digital downloads (TVOD content). That means once they buy it, they can't buy it again - so it's less about the product being available vs. not really being available a second time for the user.

Caveats include digital products that have a physical variant (like a DVD) in which case it's possible for the user to buy infinite quantities of the DVD format, but the digital product still will remain not-purchasable for themselves.

**Comment by noahott** [comment]
I've put together this functionality for Ubercart on Drupal 7: PR #114 
It includes an option to specify the number of months back it use for orders.
